title: "[ADO Proposal]: "
labels: ["ado", "proposal"]
body:
  - type: input
    id: ado-name
    attributes:
      label: Name of the ADO?
      description: Name

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: "What is the goal of this ADO and how does it function?"
    validations:
      required: true

  - type: dropdown
    id: interoperability
    attributes:
      label: Does it need to work with another ADO or is it standalone?
      options:
        - Standalone
        - Interact with other ADO
        - Mostly standalone but can interact with other ADOs
    validations:
      required: true

  - type: textarea
    id: interaction-discussion
    attributes:
      label: Where do you think this ADO fit in ecosystem?
      description: "Tell us more about this ADO interaction with other ADO"
    validations:
      required: true

  - type: textarea
    id: modules
    attributes:
      label: Modules added in ADO?
      description: "Does it implement any modules? Please provide description for any modules that this ADO will implement"

  - type: dropdown
    id: builder
    attributes:
      label: Whom would you like to develop this ADO?
      options:
        - You
        - Andromeda Team
        - External Developer from Community
    validations:
      required: true

  - type: textarea
    id: builder-description
    attributes:
      label: Do you want to add note for developer of this ADO?
      description: "Add your note here"

  - type: textarea
    id: credits
    attributes:
      label: Credits/Associations
      description: "Is this ADO based upon a previous project or ADO or in partnership with any other groups or developers? If so, please list here and provide a link if possible."

  - type: textarea
    id: resources
    attributes:
      label: Resources
      description: "Can you provide any docs/articles/research that explains the main idea of the ADO and how/why it is used?"

  - type: markdown
    attributes:
      value: |
        ## ADO Flow Breakdown
        Please list and provide descriptions of each step in the ADO flow sequence (show us how to work with the ADO and associated workflow, visuals are great here)

  - type: textarea
    id: instantiate
    attributes:
      label: Instantiate Message
      description: "Details about contract instantiation message"
      value: |
        # Instantiation
        Instantiation Details

        ### Snippet
        ```ts
        {
          "owner":"andr1...",
          "kernel_address":"andr1...",
          "other_keys":"..."
        }
        ```

    validations:
      required: true

  - type: textarea
    id: execute
    attributes:
      label: Execute Messages
      description: "Details about contract execute messages"
      value: |
        # Execute Messages

        ## Execute Message - 1
        Details about Execute Message

        ### Snippet
        ```ts
        {
          "owner":"andr1...",
          "kernel_address":"andr1...",
          "other_keys":"..."
        }
        ```

        ## Execute Message - 2
        Details about Execute Message

        ### Snippet
        ```ts
        {
          "owner":"andr1...",
          "kernel_address":"andr1...",
          "other_keys":"..."
        }
        ```

    validations:
      required: true

  - type: textarea
    id: query
    attributes:
      label: Query Messages
      description: "Details about contract query messages"
      value: |
        # Query Messages

        ## Query Message - 1
        Details about Query Message

        ### Snippet
        ```ts
        {
          "owner":"andr1...",
          "kernel_address":"andr1...",
          "other_keys":"..."
        }
        ```

        ## Query Message - 2
        Details about Query Message

        ### Snippet
        ```ts
        {
          "owner":"andr1...",
          "kernel_address":"andr1...",
          "other_keys":"..."
        }
        ```

    validations:
      required: true

  - type: textarea
    id: receive
    attributes:
      label: Receive Messages
      description: "Details about receive messages, if any"
      value: |
        ## CW20 Receive Messages
        Details about cw20 receive messages

        ## CW721 Receive Messages
        Details about cw721 receive messages

        ## Other Receive Messages
        Details about any other receive messages

  - type: textarea
    id: security
    attributes:
      label: Considerations/Concerns
      description: "What factors should be considered to mitigate risk of misuse, abuse, or other unintended scenarios, if any?"

  - type: textarea
    id: dependencies
    attributes:
      label: Any Dependencies or Third Party Integrations?
      description: "Ex. Will this ADO need to work with anything off chain, a different app, etc?"

  - type: textarea
    id: additional-snippets
    attributes:
      label: Additional Code Snippets
      description: "Snippets can help developers understand what you are trying to propose. Its highly recommended that you add snippets"
      value: |
        # Additional Snippets
        ```json
        {
          "owner":"andr1...",
          "kernel_address":"andr1...",
          "other_keys":"..."
        }

  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: The Code of Conduct helps create a safe space for everyone. We require that everyone agrees to it.
      options:
        - label: I agree to follow this project's [Code of Conduct](link/to/coc)
          required: true
